add user and item controllers
DZaparov/java-shareit pull request #1
Opened 2024-04-16 16:58 UTC by DZaparov

2024-04-17 07:02 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/handler/ErrorHandler.java
> +    public ErrorResponse handleValidationException(final ValidationException e) {
Ошибки валидации все таки BAD_REQUEST а не INTERNAL_SERVER_ERROR

2024-04-17 07:04 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/handler/ErrorHandler.java
> +}
Добавить метод с обработкой все оставшихся ошибок Throwable в INTERNAL_SERVER_ERROR

2024-04-17 07:13 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/exception/NullException.java
> +public class NullException extends RuntimeException {
Я бы переименовал, т.к. не столько с null связано,  а с тем что не заполнено обязательное поле. И нужно посмотреть можно ли вместо этого обойтись навешиванием на поля dto `@NotBlank `, чтобы по `@Valid` в контроллере проверилось.

2024-04-17 07:14 UTC, VadimZharkov requested changes
Можно улучшить

2024-04-17 07:47 UTC, DZaparov commented on src/main/java/ru/practicum/shareit/handler/ErrorHandler.java
> +    public ErrorResponse handleValidationException(final ValidationException e) {
исправлено

2024-04-17 07:47 UTC, DZaparov commented on src/main/java/ru/practicum/shareit/handler/ErrorHandler.java
> +}
добавлен метод public ErrorResponse handleThrowable(final Throwable e)

2024-04-17 10:36 UTC, DZaparov commented on src/main/java/ru/practicum/shareit/exception/NullException.java
> +public class NullException extends RuntimeException {
для create методов контроллера поля теперь проверяются по Valid,
для update методов контроллера убрал аннотацию Valid, т.к. туда могут поступать неполные объекты

2024-04-18 06:48 UTC, VadimZharkov approved these changes

2024-04-26 09:08 UTC, merged