Add item requests
DZaparov/java-shareit pull request #3
Opened 2024-05-07 15:47 UTC by DZaparov

2024-05-08 08:49 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                             @RequestParam(defaultValue = "0") int from,
Можно добавить валидацию `@PozitiveOrZero на from и @Pozitive на size `

2024-05-08 08:51 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (from < 0 || size < 0) {
size не может принимать значение 0, т.к. далее может возникнуть деление на 0

2024-05-08 08:55 UTC, VadimZharkov requested changes
Нужно еще сделать тесты для объектов  DTO с помощью аннотации `@JsonTest`

2024-05-08 11:03 UTC, DZaparov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                             @RequestParam(defaultValue = "0") int from,
аннотации добавлены

2024-05-08 11:05 UTC, DZaparov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (from < 0 || size < 0) {
условие удалено, проверка происходит на уровне контроллера с помощью аннотаций @PozitiveOrZero на from и @Pozitive на size

2024-05-09 08:12 UTC, VadimZharkov approved these changes

2024-05-09 11:28 UTC, merged